# **Numpy Arrays**

**Basic array creation**

In [ ]:
import numpy as np
a = np.array([1,2,3,4])
a
b = [[5,6,7,8], [9,10,11,12]]
np.array(b)



array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# **Array generation function**

In [ ]:
np.arange(1,12,2) #give a list of random numbers

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
np.zeros(10) #gives a list of zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((6,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(8) #gives a list of ones

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(1,5,5) # linear space is a list generator which gives a list of numbers within a range

array([1., 2., 3., 4., 5.])

# **Random generation functions**

In [ ]:
np.random.rand(10)

array([0.67445601, 0.43668262, 0.39931784, 0.00209528, 0.64639601,
       0.90782443, 0.35384013, 0.49982493, 0.31122039, 0.14842895])

In [ ]:
np.random.randint(10,20,10)

array([11, 19, 14, 11, 19, 16, 15, 16, 18, 11])

# **Array attributes**

In [ ]:
arr = np.array([[1,3,2],[4,7,5],[6,7,8]])
arr.shape

(3, 3)

In [ ]:
arr.size

9

In [ ]:
arr.dtype

dtype('int64')

# **Array methods**

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(8)

In [ ]:
arr.sum()

np.int64(43)

In [ ]:
np.sum(arr,axis=0) # when 0 column wise sum

array([11, 17, 15])

In [ ]:
np.sum(arr,axis=1) # when 1 row wise sum

array([ 6, 16, 21])

In [ ]:
arr.sort()
arr

array([[1, 2, 3],
       [4, 5, 7],
       [6, 7, 8]])

In [ ]:
arr.std()

np.float64(2.2986845406196887)

In [ ]:
arr.mean()

np.float64(4.777777777777778)

# **Reshaping and Resizing**

In [ ]:
ar = np.arange(1,11,1)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ar.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# **Array indexing and Slicing**

1. Indexing and slicing of vector

1.   Indexing and slicing of matrix
2.   Boolean indexing

**Indexing slicing of vector**

In [ ]:
arr1 = np.arange(1,10,1)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1[4]

np.int64(5)

In [ ]:
arr1[1:9:2]

array([2, 4, 6, 8])

**Indexing slicing of matrices**

In [ ]:
arr2 = np.arange(1,31,1).reshape(5,6)
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
arr2[1] # only row accessing

array([ 7,  8,  9, 10, 11, 12])

In [ ]:
arr2[1:3] #only row slicing

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [ ]:
arr2[0:6,0:1] #only column accessing

array([[ 1],
       [ 7],
       [13],
       [19],
       [25]])

In [ ]:
arr2[0:2,1:3] #accessing a particular portion

array([[2, 3],
       [8, 9]])

**Bool indexing**

In [ ]:
bool_index = arr2 %2 == 0
bool_index
arr3 = arr2[bool_index]
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

# **Array operations**

Arithmetic operation

In [ ]:
ab = np.array([1,2,3])
bc = np.array([4,5,6])

In [ ]:
ab + bc

array([5, 7, 9])

In [ ]:
ab - bc

array([-3, -3, -3])

In [ ]:
ab * bc

array([ 4, 10, 18])

In [ ]:
ab / bc

array([0.25, 0.4 , 0.5 ])

In [ ]:
ab % bc

array([1, 2, 3])

In [ ]:
ab // bc

array([0, 0, 0])

In [ ]:
ab ** bc

array([  1,  32, 729])

Boardcasting

In [ ]:
cd = np.array([1,2,3,4])
cd+1

array([2, 3, 4, 5])

Deep and shallow copy
* in deep copy changing an array can effect the main array
* but in shallow changing it doesn't affect anything
it affects in array but not list

deep copy

In [ ]:
it = np.arange(1,21)
it

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice = a[:5]
slice

array([1, 2, 3, 4])

In [ ]:
sliced = slice * 10
sliced

array([10, 20, 30, 40])

In [ ]:
it

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

shallow copy

In [ ]:
it
ti = it.copy()
ti

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
ti[3]= 763877
ti

array([     1,      2,      3, 763877,      5,      6,      7,      8,
            9,     10,     11,     12,     13,     14,     15,     16,
           17,     18,     19,     20])

Matrix operations

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [ ]:
np.dot(A,B) # dot product

array([[19, 22],
       [43, 50]])

In [ ]:
A.T # transpose

array([[1, 3],
       [2, 4]])

stacking array

In [ ]:
m = np.array([1,2,3])
n = np.array([4,5,6])

In [ ]:
np.vstack((m,n))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack((m,n))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.column_stack((m,n))

array([[1, 4],
       [2, 5],
       [3, 6]])

splitting array

In [ ]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

# **Numpy Exercises**